Дана целочисленная прямоугольная матрица. Определить:
- количество положительных элементов в тех строках, которые не содержат нулевых
элементов;
- номера строк и столбцов всех седловых точек матрицы.

Примечание. Матрица А имеет седловую точку А если А является минимальным
элементом в -i строке и максимальным в -j столбце.

Задание 1.

In [2]:
import numpy as np
matr = np.random.randint(-9, 10, size = (20, 15))
print(matr)

[[ 3  1  2 -6  0  0 -6  4  0 -3  8  0  3  9  4]
 [ 7  0  4 -5  1  4  2 -4 -2 -3  7  7 -1 -3  5]
 [ 1  4 -6 -4 -5  6  2 -7  2 -4 -6  6 -9  1 -8]
 [ 7  5  2  4 -4  6 -2 -6  5 -5  1 -6  6  0  5]
 [ 9 -9  9  4  2  5 -5 -7  9 -5  1  1 -2  4 -9]
 [ 6  9 -4  1  3  6  6 -1  1 -4 -9 -6 -9  6 -3]
 [ 9 -1 -1 -1 -6  1  6  9 -1 -9  5  1  5 -2 -6]
 [-5 -2  3 -5  8 -8 -2  4  9  8 -9  5  2  3 -9]
 [ 2  6  7  7  3 -9 -9 -9  9 -7  1 -9 -7 -1 -4]
 [-1  5  4 -8  3 -8 -7 -5  1 -2  5 -9  8  6  5]
 [-1  0  8 -4  9  6 -4  4 -6 -6  2 -1 -7 -7 -2]
 [-7  0  3  8 -9  4 -4  9 -4 -6  9  7  3 -9  8]
 [-8 -3  6  1 -6  5 -1  5 -7 -1  9  0 -5  5 -9]
 [ 7 -7 -6 -5  4  1  5 -8  0  9 -5 -9  8 -7  8]
 [-9 -1  3 -8  6 -2  7 -6  8  4  9  5 -5 -8 -3]
 [ 2 -3 -4  7  4 -5  2 -9  4 -3 -6 -8  9 -6  3]
 [ 9 -2 -7 -3  7 -3  4  6  7 -4  8 -6  0  8  0]
 [ 3 -2  5  5 -5 -4  2  2 -3  7  9  8 -4 -5 -4]
 [-3 -9  4 -3  3  8 -8  3 -3 -4  2  2 -7 -6  8]
 [ 0 -7 -6  9  5  1  7  7  9  5 -7 -3 -3 -8 -3]]


In [3]:
a = (matr != 0).all(axis=1)
b = matr[a, :]
b

array([[ 1,  4, -6, -4, -5,  6,  2, -7,  2, -4, -6,  6, -9,  1, -8],
       [ 9, -9,  9,  4,  2,  5, -5, -7,  9, -5,  1,  1, -2,  4, -9],
       [ 6,  9, -4,  1,  3,  6,  6, -1,  1, -4, -9, -6, -9,  6, -3],
       [ 9, -1, -1, -1, -6,  1,  6,  9, -1, -9,  5,  1,  5, -2, -6],
       [-5, -2,  3, -5,  8, -8, -2,  4,  9,  8, -9,  5,  2,  3, -9],
       [ 2,  6,  7,  7,  3, -9, -9, -9,  9, -7,  1, -9, -7, -1, -4],
       [-1,  5,  4, -8,  3, -8, -7, -5,  1, -2,  5, -9,  8,  6,  5],
       [-9, -1,  3, -8,  6, -2,  7, -6,  8,  4,  9,  5, -5, -8, -3],
       [ 2, -3, -4,  7,  4, -5,  2, -9,  4, -3, -6, -8,  9, -6,  3],
       [ 3, -2,  5,  5, -5, -4,  2,  2, -3,  7,  9,  8, -4, -5, -4],
       [-3, -9,  4, -3,  3,  8, -8,  3, -3, -4,  2,  2, -7, -6,  8]])

In [4]:
np.sum(b > 0)

83

Задание 2.

In [5]:
m = np.random.randint(-2, 2, size = (4, 3))
print(m)

[[-1  1 -1]
 [ 1  0  0]
 [ 0  1 -1]
 [-1 -1  1]]


In [6]:
min_list_index = []
z = np.min(m, axis=1)
for i, (row, value_min) in enumerate(zip(m, z)):
    for j, item_min in enumerate(row):
        if value_min == item_min:
            tpl_min = (i, j)
            min_list_index.append(tpl_min)
print(min_list_index)

[(0, 0), (0, 2), (1, 1), (1, 2), (2, 2), (3, 0), (3, 1)]


In [9]:
max_list_index = []
x = np.max(m, axis=0)
for k, (col, value_max) in enumerate(zip(m, x)):
    for l, item_max in enumerate(col):
        if value_max == item_max:
            tpl_max = (l, k)
            max_list_index.append(tpl_max)
print(max_list_index)

[(1, 0), (0, 1), (1, 2)]


In [8]:
for min_idx in min_list_index:
    for max_idx in max_list_index:
        if min_idx == max_idx:
            print(f'{min_idx} - седловая точка матрицы')          

(1, 2) - седловая точка матрицы
